#v2.1
openapi: 3.0.0
servers:
  - url: https://devtemplate.qbitum.net
    description: development server
info:
  description: >-
    This is services apis.
  version: 1.0.0
  title: APIs
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /v1/sample:
    get:
      tags:
        - web
      summary: API summary
      description: API description
      operationId: summaryID
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          description: Bearer Token for Authorization
          schema:
            type: string
        - name: X-Client-Id
          in: header
          description: client ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "message to display when the API is successfull"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Summary"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

# comment
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - status
        - message
      properties:
        code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string
    Summary:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/Overview"
    Overview:
      type: object
      required:
        - "jobStatus"
        - "totalNoOfJobs"
      properties:
        jobStatus:
          type: string
        totalNoOfJobs:
          type: number
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
