version: "3"

services:
  next-app:
    container_name: saastack-im-app
    build:
      context: ../
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes: 
      - ../src:/app/src
      - ../public:/app/public
      - ../saastack-react:/app/saastack-react
    restart: always
    ports:
      - 4000:4000
    networks:
      - saastack_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  saastack_network:
    external: true
